theme: jekyll-theme-cayman  # <--- Change this name to swap themes!
title: The Last PM v3.0.0
description: The Autonomous Product OS for Cursor & Claude.

exclude:
  - 00_OS_System_Files/
  - 01_Global_Context/
  - 02_Product_Workspace/
  - 04_Agents/
  - LastPM.md
