remote_theme: cotes2020/jekyll-theme-chirpy
title: The Last PM v3.0.0
description: The Autonomous Product OS for Cursor & Claude.

# Modern themes often need a baseurl setting
baseurl: "/LastPM" 
url: "https://jdamiri.github.io"

exclude:
  - "00_OS_System_Files"
  - "01_Global_Context"
  - "02_Product_Workspace"
  - "04_Agents"
  - "LastPM.md"
  - "vendor"
  - "Gemfile"
  - "Gemfile.lock"
